module Raylib
  def init_window                : (width: Integer, height: Integer, title: String) -> void
  def close_window               : ()                                               -> void
  def begin_drawing              : ()                                               -> void
  def end_drawing                : ()                                               -> void
  def toggle_fullscreen          : ()                                               -> void
  def toggle_borderless_windowed : ()                                               -> void
  def maximize_window            : ()                                               -> void
  def minimize_window            : ()                                               -> void
  def restore_window             : ()                                               -> void
  def window_should_close        : ()                                               -> bool
  def is_window_ready            : ()                                               -> bool
  def is_window_fullscreen       : ()                                               -> bool
  def is_window_hidden           : ()                                               -> bool
  def is_window_minimized        : ()                                               -> bool
  def is_window_maximized        : ()                                               -> bool
  def is_window_focused          : ()                                               -> bool
  def is_window_resized          : ()                                               -> bool
  def set_window_state           : (flags: Integer)                                 -> void
  def clear_window_state         : (flags: Integer)                                 -> void
  def is_window_state            : (flags: Integer)                                 -> bool
  def set_trace_log_level        : (level: Integer)                                 -> bool
  def clear_background           : (color: Color)                                   -> void
end
